# Generated by Django 5.2.9 on 2026-01-13 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_customuser_publisher_memberships_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='published_articles',
            field=models.ManyToManyField(blank=True, related_name='independent_publishers', to='news.article'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'editor'}, related_name='publishers_as_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'journalist'}, related_name='publishers_as_journalist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='journalist',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'journalist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.publisher'),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journalist', models.ForeignKey(blank=True, limit_choices_to={'role': 'journalist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters_written', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='news.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='published_newsletters',
            field=models.ManyToManyField(blank=True, related_name='independent_publishers', to='news.newsletter'),
        ),
    ]
