from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    home,
    register,
    review_articles,
    approve_article,
    editor_articles,
    editor_article_edit,
    editor_article_delete,
    editor_newsletters,
    editor_newsletter_edit,
    editor_newsletter_delete,
    journalist_articles,
    create_article,
    journalist_article_edit,
    journalist_article_delete,
    journalist_newsletters,
    create_newsletter,
    journalist_newsletter_edit,
    journalist_newsletter_delete,
    get_articles,
    articles,
    article_detail,
    publisher_list,
    publisher_create,
)

urlpatterns = [
    path("", home, name="home"),
    path("login/", auth_views.LoginView.as_view(template_name="news/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", register, name="register"),
    path("articles/", articles, name="articles"),
    path("articles/<int:pk>/", article_detail, name="article_detail"),
    path("editor/articles/review/", review_articles, name="review_articles"),
    path("editor/articles/<int:pk>/approve/", approve_article, name="approve_article"),
    path("editor/articles/", editor_articles, name="editor_articles"),
    path("editor/articles/<int:pk>/edit/", editor_article_edit, name="editor_article_edit"),
    path("editor/articles/<int:pk>/delete/", editor_article_delete, name="editor_article_delete"),
    path("editor/newsletters/", editor_newsletters, name="editor_newsletters"),
    path("editor/newsletters/<int:pk>/edit/", editor_newsletter_edit, name="editor_newsletter_edit"),
    path("editor/newsletters/<int:pk>/delete/", editor_newsletter_delete, name="editor_newsletter_delete"),
    path("journalist/articles/", journalist_articles, name="journalist_articles"),
    path("journalist/articles/new/", create_article, name="create_article"),
    path("journalist/articles/<int:pk>/edit/", journalist_article_edit, name="journalist_article_edit"),
    path("journalist/articles/<int:pk>/delete/", journalist_article_delete, name="journalist_article_delete"),
    path("journalist/newsletters/", journalist_newsletters, name="journalist_newsletters"),
    path("journalist/newsletters/new/", create_newsletter, name="create_newsletter"),
    path("journalist/newsletters/<int:pk>/edit/", journalist_newsletter_edit, name="journalist_newsletter_edit"),
    path("journalist/newsletters/<int:pk>/delete/", journalist_newsletter_delete, name="journalist_newsletter_delete"),
    path("publishers/", publisher_list, name="publisher_list"),
    path("publishers/new/", publisher_create, name="publisher_create"),
    path("api/articles/", get_articles, name="get_articles"),
]